CREATE TABLE IF NOT EXISTS accounts(
  id VARCHAR(255) NOT NULL primary key COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  name varchar(255) COMMENT 'User Name',
  email varchar(255) COMMENT 'User Email',
  picture varchar(255) COMMENT 'User Picture'
) default charset utf8 COMMENT '';
CREATE TABLE IF NOT EXISTS contractors(
  name VARCHAR(255) NOT NULL,
  specialty VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY
) default charset utf8;
CREATE TABLE IF NOT EXISTS companies(
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY
) default charset utf8;
CREATE TABLE IF NOT EXISTS jobs(
  contractorId INT NOT NULL,
  companyId INT NOT NULL,
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  FOREIGN KEY(contractorId) REFERENCES contractors(id) ON DELETE CASCADE,
  FOREIGN KEY(companyId) REFERENCES companies(id) ON DELETE CASCADE
) default charset utf8;

INSERT INTO jobs (contractorId, companyId)
VALUES (1, 4);

SELECT * FROM jobs;

SELECT 

FROM jobs j
JOIN 
WHERE 